name: quiz_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_auth_web: ^5.8.13
  firebase_database: ^11.1.6
  cloud_firestore: ^5.6.6
  provider: ^6.1.4
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg.jpeg
    - assets/images/icon.jpeg
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/avatars/camion.jpeg
    - assets/images/avatars/cat.jpeg
    - assets/images/avatars/girly.jpeg
    - assets/images/avatars/temseh.jpeg
    - assets/images/avatars/aqroub.jpeg
    - assets/images/avatars/black_cat.jpeg
    - assets/images/avatars/couchon.jpeg
    - assets/images/avatars/dabdoub.jpeg
    - assets/images/avatars/dhib.jpeg
    - assets/images/avatars/fil.jpeg
    - assets/images/avatars/nahla.jpeg
    - assets/images/avatars/mafjouu.jpeg
    - assets/images/avatars/far.jpeg