// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFgnDsQjEmL1lv-inftvnRW9A5_UAaL2E',
    appId: '1:319338333575:web:8e6053283e2475f8cdbf22',
    messagingSenderId: '319338333575',
    projectId: 'quiz-75031',
    authDomain: 'quiz-75031.firebaseapp.com',
    storageBucket: 'quiz-75031.firebasestorage.app',
    measurementId: 'G-8FF8MJ0HCG',
    databaseURL: 'https://quiz-75031-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_yazvbZm61mEOt_xI0pQhL9pMmnVMuLA',
    appId: '1:319338333575:android:d54ec26ec45d17eccdbf22',
    messagingSenderId: '319338333575',
    projectId: 'quiz-75031',
    storageBucket: 'quiz-75031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHL0z4hC-IiZgYTv030fKs2eJm-jSomkw',
    appId: '1:319338333575:ios:ed0e78dc824d74bbcdbf22',
    messagingSenderId: '319338333575',
    projectId: 'quiz-75031',
    storageBucket: 'quiz-75031.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHL0z4hC-IiZgYTv030fKs2eJm-jSomkw',
    appId: '1:319338333575:ios:ed0e78dc824d74bbcdbf22',
    messagingSenderId: '319338333575',
    projectId: 'quiz-75031',
    storageBucket: 'quiz-75031.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFgnDsQjEmL1lv-inftvnRW9A5_UAaL2E',
    appId: '1:319338333575:web:1489d57d70a2324acdbf22',
    messagingSenderId: '319338333575',
    projectId: 'quiz-75031',
    authDomain: 'quiz-75031.firebaseapp.com',
    storageBucket: 'quiz-75031.firebasestorage.app',
    measurementId: 'G-LNCV1SJTWH',
  );
}
